"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";

const professionals=["Any available artist","Morgan Reed","Avery Lane","Jordan Blake","Riley Hart","Casey Monroe","Taylor Quinn","Cameron Sage","Parker Ellis"];
type Service={id:number;category:string;name:string;priceCents:number;durationMinutes:number;detail:string;addOns:string};
const durationLabel=(minutes:number)=>minutes>=60?`${Math.floor(minutes/60)} hr${minutes%60?` ${minutes%60} min`:""}`:`${minutes} min`;
const isoDate=(offset:number)=>{const date=new Date();date.setDate(date.getDate()+offset);return date.toISOString().slice(0,10)};
const displayDate=(value:string)=>new Intl.DateTimeFormat("en-US",{weekday:"short",month:"short",day:"numeric"}).format(new Date(`${value}T12:00:00`));
const displayTime=(value:string)=>new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit"}).format(new Date(`2026-01-01T${value}:00`));

export default function BookingPage(){
 const params=useSearchParams(), requested=params.get("stylist");
 const [step,setStep]=useState(1),[stylist,setStylist]=useState(requested&&professionals.includes(requested)?requested:professionals[0]);
 const [service,setService]=useState<Service|null>(null),[date,setDate]=useState(isoDate(1)),[time,setTime]=useState("10:00"),[confirmed,setConfirmed]=useState(false);
 const [services,setServices]=useState<Service[]>([]),[selectedAddOns,setSelectedAddOns]=useState<string[]>([]);
 const [bookedTimes,setBookedTimes]=useState<string[]>([]),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const [availability,setAvailability]=useState<{workDays?:string;startTime?:string;endTime?:string;breakStart?:string|null;breakEnd?:string|null}>({}),[blocks,setBlocks]=useState<{startTime:string|null;endTime:string|null}[]>([]);
 const dates=useMemo(()=>[1,2,3,4,5,6,7].map(isoDate).filter(value=>new Date(`${value}T12:00:00`).getDay()!==0).slice(0,5),[]);
 const times=useMemo(()=>["09:30","10:00","11:15","13:30","15:00","17:15"],[]);
 const groups=useMemo(()=>Array.from(new Set(services.map(item=>item.category))).map(title=>({title,items:services.filter(item=>item.category===title)})),[services]);
 useEffect(()=>{setService(null);setSelectedAddOns([]);fetch(`/api/services?stylist=${encodeURIComponent(stylist)}`).then(r=>r.json()).then(data=>setServices(data.services||[])).catch(()=>setServices([]))},[stylist]);
 useEffect(()=>{if(step!==3)return;fetch(`/api/appointments?availability=1&stylist=${encodeURIComponent(stylist)}&date=${date}`).then(r=>r.json()).then(data=>{setBookedTimes(data.bookedTimes||[]);setAvailability(data.settings||{});setBlocks(data.blocks||[])}).catch(()=>setBookedTimes([]))},[step,stylist,date]);
 const unavailable=(t:string)=>{const day=new Date(`${date}T12:00:00`).getDay();if(availability.workDays&&!availability.workDays.split(",").includes(String(day)))return true;if(availability.startTime&&t<availability.startTime)return true;if(availability.endTime&&t>=availability.endTime)return true;if(availability.breakStart&&availability.breakEnd&&t>=availability.breakStart&&t<availability.breakEnd)return true;return bookedTimes.includes(t)||blocks.some(b=>!b.startTime||(t>=b.startTime&&(!b.endTime||t<b.endTime)))};
 if(confirmed)return <main className="booking-shell confirmation"><Link className="booking-logo" href="/"><span className="wordmark">Juniper <em>Studio</em></span></Link><div className="confirmation-mark">✓</div><p className="eyebrow">Appointment confirmed</p><h1>You&apos;re on the books.</h1><p>Your appointment is saved with <strong>{stylist}</strong> for <strong>{service?.name}</strong> on <strong>{displayDate(date)} at {displayTime(time)}</strong>.</p><div className="confirmation-card"><span>Payment</span><strong>Pay your stylist directly after your visit</strong><small>Your artist will share their preferred Zelle, Venmo, Cash App, or Square instructions.</small></div><Link className="button button-dark" href="/">Back to Juniper Studio</Link></main>;
 return <main className="booking-shell">
  <header className="booking-header"><Link className="booking-logo" href="/"><span className="wordmark">Juniper <em>Studio</em></span></Link><Link className="close-link" href="/">Close ×</Link></header><div className="booking-progress"><span style={{width:`${step*25}%`}}/></div>
  <div className="booking-layout"><section className="booking-main">
   {step===1&&<><p className="eyebrow">Step 1 of 4</p><h1>Who would you like to see?</h1><p className="booking-lead">Choose your artist, or let us find the first available appointment.</p><div className="choice-grid">{professionals.map((person,i)=><button className={`person-choice ${stylist===person?"selected":""}`} key={person} onClick={()=>setStylist(person)}><span>{i===0?"✦":person.split(" ").map(n=>n[0]).join("")}</span><div><strong>{person}</strong><small>{i===0?"Best for flexible schedules":"Independent studio artist"}</small></div><b>→</b></button>)}</div><button className="button button-dark next-button" onClick={()=>setStep(2)}>Continue</button></>}
   {step===2&&<><p className="eyebrow">Step 2 of 4</p><h1>Choose your service.</h1><p className="booking-lead">You&apos;re seeing the live menu, timing, and pricing set by {stylist}.</p>{groups.map(group=><div className="service-choice-group" key={group.title}><h2>{group.title}</h2>{group.items.map(item=><div key={item.id}><button className={`service-choice ${service?.id===item.id?"selected":""}`} onClick={()=>{setService(item);setSelectedAddOns([])}}><div><strong>{item.name}</strong><small>{item.detail}</small><span>{durationLabel(item.durationMinutes)}</span></div><b>{item.priceCents?`From $${item.priceCents/100}`:"Complimentary"}</b><i>{service?.id===item.id?"✓":"+"}</i></button>{service?.id===item.id&&item.addOns&&<div className="booking-addons"><strong>Optional add-ons</strong>{item.addOns.split("|").filter(Boolean).map(addon=><label key={addon}><input type="checkbox" checked={selectedAddOns.includes(addon)} onChange={()=>setSelectedAddOns(v=>v.includes(addon)?v.filter(x=>x!==addon):[...v,addon])}/>{addon}</label>)}</div>}</div>)}</div>)}{!services.length&&<p className="inline-empty">Loading this artist&apos;s service menu…</p>}<div className="step-actions"><button className="text-button" onClick={()=>setStep(1)}>← Back</button><button disabled={!service} className="button button-dark" onClick={()=>setStep(3)}>Choose a time</button></div></>}
   {step===3&&<><p className="eyebrow">Step 3 of 4</p><h1>Pick a date and time.</h1><p className="booking-lead">Showing live openings for {stylist}, including their working hours, breaks, and time off.</p><div className="date-strip">{dates.map(d=>{const parts=displayDate(d).replace(",","").split(" ");return <button className={date===d?"selected":""} onClick={()=>{setDate(d);setTime("")}} key={d}><small>{parts[0]}</small><strong>{parts[2]}</strong><span>{parts[1]}</span></button>})}</div><div className="time-grid">{times.map(t=><button disabled={unavailable(t)} className={time===t?"selected":""} onClick={()=>setTime(t)} key={t}>{unavailable(t)?"Unavailable":displayTime(t)}</button>)}</div><div className="step-actions"><button className="text-button" onClick={()=>setStep(2)}>← Back</button><button disabled={!time||unavailable(time)} className="button button-dark" onClick={()=>setStep(4)}>Continue</button></div></>}
   {step===4&&<><p className="eyebrow">Step 4 of 4</p><h1>Almost there.</h1><p className="booking-lead">Tell your artist where to send the confirmation.</p><form className="client-form" onSubmit={async e=>{e.preventDefault();setSaving(true);setError("");const form=new FormData(e.currentTarget);const note=[String(form.get("notes")||""),selectedAddOns.length?`Requested add-ons: ${selectedAddOns.join(", ")}`:""].filter(Boolean).join("\n");const response=await fetch("/api/appointments",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({fullName:form.get("fullName"),email:form.get("email"),phone:form.get("phone"),notes:note,stylist,service:service?.name,serviceDate:date,serviceTime:time,durationMinutes:service?.durationMinutes||60,priceCents:service?.priceCents||0})});const data=await response.json();setSaving(false);if(response.ok)setConfirmed(true);else setError(data.error||"Please try another time.")}}><label>Full name<input name="fullName" required placeholder="Your name"/></label><div><label>Email<input name="email" required type="email" placeholder="you@email.com"/></label><label>Mobile number<input name="phone" required type="tel" placeholder="(480) 555-0123"/></label></div><label>Anything your stylist should know?<textarea name="notes" placeholder="Hair history, inspiration, accessibility needs..."/></label><label className="checkbox"><input type="checkbox" required/> I understand Juniper Studio&apos;s 24-hour cancellation policy.</label><div className="payment-note"><span>$</span><div><strong>Pay your artist directly</strong><small>No payment is collected online. Each independent artist provides their own payment link or instructions.</small></div></div>{error&&<p className="form-error" role="alert">{error}</p>}<div className="step-actions"><button type="button" className="text-button" onClick={()=>setStep(3)}>← Back</button><button disabled={saving} className="button button-dark" type="submit">{saving?"Saving…":"Confirm appointment"}</button></div></form></>}
  </section><aside className="booking-summary"><p className="eyebrow">Your appointment</p><h2>{service?.name||"Select a service"}</h2><div><span>Artist</span><strong>{stylist}</strong></div>{step>=3&&<div><span>When</span><strong>{displayDate(date)}<br/>{time&&displayTime(time)}</strong></div>}{service&&<><div><span>Duration</span><strong>{durationLabel(service.durationMinutes)}</strong></div><div><span>Starting at</span><strong>{service.priceCents?`$${service.priceCents/100}`:"Complimentary"}</strong></div>{selectedAddOns.length>0&&<div><span>Add-ons</span><strong>{selectedAddOns.join(", ")}</strong></div>}</>}<small>Prices vary by artist and may change based on hair length, density, and product used.</small></aside></div>
 </main>;
}
